### ISSUE TITLE
No music in areas

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#133]
Player reports there is no music in any of the areas besides the starting area. Take a look at the existing areas and add music if it's missing.

**Comment by Drakaden** [comment]
Checked areas, some areas does not contain music, others that does have a glitch bug from EE edition, will add music to areas that does not have any when bug is fixed on their part.

**Comment by Drakaden** [comment]
They fixed the music bug, i added music to all areas, sent module to Zun.
