### ISSUE TITLE
Door transits in same areas not giving sanctuary effect

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#140]
Some transits leading in the same area does not trigger a sanctuary effect, making players being targeted by the zombies right away without seeing what's going on.

**Comment by zunath** [comment]
The sanctuary effect was designed to help players out if they take a while to load the area. However, transitioning within the same area doesn't cause a loading screen so for that reason I'm going to leave it as-is.
