### ISSUE TITLE
Armors rebalancing suggestions

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#141]
**_Clothes:_**

AMP Integrated suit:
Enhancement +1
Evocation +1
Holy +1
Skill requirements: Armor 1, Mana 2

Suggested change:
-1 to AC due to the equipment installed in the suit, it enhance the user, but at the cost of the suit being less mobile from it.

---

Hunting vest:
Constitution +1
Dexterity +2
Cast speed penalty 10%
AC penalty -1
Inventory space +2
Hide +1
Skill requirements: Armor 2, dexterity 2

Suggested change:
Remove decrease AC -1, the logic behind this change is that mobile clothes allow to dodge blows, these are light clothes, they do not soak any damage, but they are made to be mobile, also the AC penalty come nullify the benefits of dexterity +2.

---

Plate reinforced coat:
AC +4
Cast speed penalty 20%
Soak 3 damage
Dexterity penalty -2
Skill requirements: Armor 3, strength 2

Suggested change:
Remove the 4 AC, heavier armor does not allow more mobility, it in fact hinder it, the dexterity -2 come give a -1 to AC, which translate as less dodging, the soak itself it a huge benefit in itself, and the plates does just that, a big perk no other types of armors have. To compensate, add Constitution +1, as it translate to being more durable.

---

Metal riot shield:
Base AC 3
AC +3
Cast speed penalty 25%
Ballistic resist 5/
Bullet resist 5/
Dexterity penalty -1
Skill requirement: Armor 6

Suggested change:
Lower the +3 to AC to +1, shields are indeed made to deflect and absorb some damage, though this particular shield has been overly powered by the AC which make a character a dodging ninja when equipped, lowering the AC to +1 make the total AC equaling to 4 for this shield, which is better than the Repurposed Fence in every aspects.

---

**_Belts:_**

Battler plate:
Constitution +2
AC +5
Cast speed penalty 75%
Soak 4 damage
Dexterity penalty -3
Hide penalty -1
Move silently penalty -2
Tumble penalty -1
Weight increase 15 lbs
Skill requirement: Armor 6

Suggested change:
Add skill requirement strength 4, as this is easily one of the most heavy armor around. Remove AC +5, its heavy, it does not allow to dodge more, it soak more and is more durable. Decrease tumble from -1 to -3, it's heavy, very heavy. Raise soak from 4 to 5, it's made to withstand blows.

---

Any belts that is caster related named ROBES:
Decreased AC -1, robes hinder mobility.

---

Gun belt:
Constitution +1
Dexterity +1
Inventory space +1
Skill requirements: Armor 2, Dexterity 2

Suggested change:
Either make it dexterity +2 or add +1 to AC, this belt is supposed to help speed with gunslingers, so dexterity +2 would make sense, especially because due to the fact that +1 to a stat does not give any benefits.

---

Gutter Knight Plate:
AC +3
Cast speed penalty 35%
Soak 3 damage
Dexterity penalty -1
Hide penalty -1
Move silently -2
Weight increase 15 lbs
Skill requirement: Armor 3

Suggested change:
This is the middle child between Plate Reinforced Coat and Battler Plate, remove the AC +3, raise soak from 3 to 4, add skill requirement strength 3, raise armor from 3 to 4, add Constitution +1. Lower Dexterity from -1 to -2 to be up par with the Plate Reinforced Coat penalty.

---

Infantry Vest:
AC +2
Cast speed penalty 15%
Inventory space +1
Skill requirement: Armor 2

Suggested change:
Add Tumble +1, infantry clothes are made to be mobile for all situations.

---

Infiltrator Vest:
Dexterity +1
AC +1
Cast speed penalty 10%
Skill requirement: Armor 2

Suggested change:
Add Hide +1, it's made for infiltration.

---

Makeshift Armor:
AC +1
Cast speed penalty 99%
Soak 1 damage
Skill requirement: Armor 2, Dexterity 1, Strength 1

Suggested change:
Cast speed penalty changed from 99% to 10%, for obvious reasons. Add Tumble +1.

---

**_Boots:_**

Armored Boots:
Constitution +1
AC +1

Suggested change:
Remove the AC +1, it's armor, it's not mobile. Raise Constitution to +2, lower Move Silently by -1.

---

Plated Boots:
Same thing as Armored Boots, suggesting updating these boots and deleting the older version Armored Boots.

---

**_Backpacks items:_**

Duplicates noticed, server use Cloak for those, duplicates spotted in Belt, suggests deleting the old belt ones.

---

**_Gloves:_**

Pneumatic Sleeves:
Constitution +2
Strength +3
Skill requirements: Armor 2, Constitution 3

***Fixed a typo to Pneumatic in my module**

Suggested change:
These gloves are too powerful for tier 1 and their low requirements: Lower constitution to +1, lower strength to +2.

---

**Comment by zunath** [comment]
In NWN, AC is not "evasion". It's your ability to mitigate attacks. I don't necessarily agree with the approach personally, but that's how it works.

Many of the items you've listed aren't available in game anymore.

G-Nome spent a lot of time on balancing these items and we had a lot of discussions. I feel they're in a good place now. I want to look to advancing beyond tier 1 now.

Thanks for fixing the typo.
