### ISSUE TITLE
Item add properties

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#142]
Suggesting making Gun firing speed bonus/penalty, Movement speed bonus/Penalty and Melee attack speed bonus/penalty.

**Comment by zunath** [comment]
Attack speed changes are not possible right now. Everything is on a six second timer. In the future, this could become possible but right now it's not.

Animations do not play while you're moving so a movement speed bonus/penalty isn't possible.
