### ISSUE TITLE
Starting professions overhaul

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#143]
Instead of starting with professions that gives various pros at different values, start with a profession allocation amount, and decide which perks to buy, each perk having a different value.

Example:
10 Profession Allocation Pts.
All perks chosen can go OVER the cap, but cannot be taken more than the allowed amount.
Search +1 (max 1): 1 pt
Handgun Proficiency +1 (max 1): 2 pts
Evocation +1 (max 1): 2 pts
Inventory Space (max 3): 1 pt

And so on, this way people can tailor their characters.

**Comment by taelon875** [comment]
Or you can choose the profession that starts you out with six skill points instead?

**Comment by zunath** [comment]
I'm not overhauling professions and I'm definitely not doing this. Use the Vagabond if you want customization.
