### ISSUE TITLE
Dexterity description: To add tumble to it

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#147]
Each dexterity point raise tumble by 1.

**Comment by taelon875** [comment]
There is a tumble skill. No need for both. Besides as a NWN passive every 2 points of DEX adds 1 tumble (and any other DEX based skill)

**Comment by Drakaden** [comment]
I'll just correct you, i have 1 tumble, and 14 dexterity, i do a tumble of 5 tumble, hence it is 1 tumble for every dexterity point.

**Comment by taelon875** [comment]
Sounded as if you were suggesting that, it shouldn't be giving 1 tumble per rank. That needs to be fixed seeing as that is a skill.

**Comment by zunath** [comment]
Drak's right on this one. I'll update the description.
