### ISSUE TITLE
Suggestion: Melee weapons damage to be doubled or tripled

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#163]
Redcrayon suggested in-game that melee weapons should deal double or triple the damage they do to make up for their lack of speed, possible temporary solution until we get melee speed?

**Comment by zunath** [comment]
Adjusting the melee combat speed isn't possible at the moment (but may become possible in the future?)

Do you mean additional attacks per round?

**Comment by taelon875** [comment]
Additional attacks per round.

**Comment by zunath** [comment]
That makes sense to me. I see it potentially as a new skill upgrade

**Comment by Drakaden** [comment]
Just a reminder, the default additional attacks per round from nwn lower the accuracy of each attack

**Comment by taelon875** [comment]
Okay, a perk that increase ab by one each time, and every 5 it adds a additional attack per round?

**Comment by Drakaden** [comment]
It's a good idea Collin, however attack bonus would need modified because attack bonus does not apply if it's not on the weapon itself, the alternate way would be to give a temporary effect to the weapon, which wear off when unequipped.

**Comment by taelon875** [comment]
or base attack? that applies on character...
I believe that increases ab also.

**Comment by Drakaden** [comment]
Base attack would indeed work for this, and it would improve throwing weapons ins ame time (darts and such) since they are affected by that.

**Comment by zunath** [comment]
This is in game now.
