### ISSUE TITLE
Regeneration When Cast on ZOmbies

### ISSUE THREAD

**Issue by taelon875** [zunath/CyberpunkZombieSurvival_JVM#166]
It regenerates zombies when cast upon them.

**Comment by zunath** [comment]
Expected behaviour: 

Either:
1.) Don't allow players to cast it on zombies/enemies.
or
2.) Have it deal damage to them instead of healing.

**Comment by taelon875** [comment]
1 makes more sense in RP. 
2 would allow for a small offensive spell for holy casters Which i think could make them a little more viable as a main choice.

**Comment by zunath** [comment]
I prevent it from firing if target is undead. I think we'll go with adding another ability for dealing damage in the Holy spec.
