### ISSUE TITLE
Necklace item slot

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#173]
Currently unused for gear, need made and blueprint added.

**Comment by Drakaden** [comment]
Suggestion for amulets:

T1:
Warrior's Zeal
Bonus feat: Cleave

Cat's Sight
Bonus feat: Dark vision

Escapist's Prowess
Bonus feat: Dodge

Brawler's Knowledge
Bonus feat: Improved Unarmed Strike

Escapist's Fleeting Steps
Bonus feat: Mobility

Berzerker's Fury
Bonus feat: Power Attack

Assassin's Wit
Bonus feat: Sneak Attack +1d6

---

T2 Amulets:

Warrior's Storm
Bonus feat: Whirlwind

Cat's Instincts
Bonus feat: Dark vision
Damage bonus: Piercing (1d4)

Escapist's Proficiency
Bonus feat: Dodge
Bonus feat: Mobility

Brawler's Proficiency
Bonus feat: Improved Unarmed Strike
Bonus feat: Weapon specialization (Unarmed)

Berzerker's Vengeance
Bonus feat: Power Attack
On Hit: Wounding (Preferably replace this with the custom bleeding from zombies, as Wounding never stops until healed)

Assassin's Knowledge
Bonus feat: Sneak attack 2d6

---

T3 amulets:

Warrior's Mastery
Bonus feat: Cleave
Bonus feat: Whirlwind

Cat's Intelligence
Bonus feat: Dark vision
Damage bonus: Piercing (1d4)
AC + 1

Escapist's Mastery
Bonus feat: Dodge
Bonus feat: Mobility
AC +1

Brawler's Mastery
Bonus feat: Improved Unarmed Strike
Bonus feat: Weapon specialization (Unarmed)
Bonus feat: Improved Critical (Unarmed)

Berzerker's Immortal Prowess
Bonus feat: Power Attack
On Hit: Wounding (Preferably replace this with the custom bleeding from zombies, as Wounding never stops until healed)
Keen

Assassin's Proficient Knowledge
Bonus feat: Sneak attack 3d6

**Comment by zunath** [comment]
I'd personally like to see the feats added as abilities instead of having them on items. That said, I could see amulets providing raw Mana/HP upgrades or perhaps tweaking the effects of some spells.

**Comment by zunath** [comment]
This isn't an approach I want to take with necklace slots.
