### ISSUE TITLE
Infection DC check

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#175]
I find it suspcious that my DC against infection ias as bad as a con 10 player as i have 22 which is +6, worth investigating

**Comment by Drakaden** [comment]
http://prntscr.com/j2cgl6

**Comment by zunath** [comment]
Your con modifier is 6 and you got a roll of 0. I don't think it should be possible to roll a 0 so I'm bumping that to a minimum of 1 but other than that it looks like it's working as intended.
