### ISSUE TITLE
Add Weapon Finesse ability

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#176]
Need to add NWN's weapon finesse ability to the game. Player recommends we also give it a 1d6 sneak damage when equipped. Open for discussion on that one.

**Comment by NariKat** [comment]
Sounds good to me. The 1d6 sneak is pretty weak, so I don't see an issue with it. For it to take effect the zombie needs to be either unaware of the player, or engaged in combat with another target so... either the character waits for the zombie to be fighting another character and then attack them, or she has to sneak up on a zombie and attack it (which reveals the character and stops any further sneak attacks). I only see this could be abused if the player kept sneaking-hit-run around corner to get lots of low-risk +d6 damage.

**Comment by taelon875** [comment]
For sneak I think we would have to also remove Zombies immunity to it if we add it I believe.

**Comment by NariKat** [comment]
Good point. I assumed they werent' immune to sneak already as they aren't to crits.
