### ISSUE TITLE
Add T2 Gear to Loot Tables

### ISSUE THREAD

**Issue by taelon875** [zunath/CyberpunkZombieSurvival_JVM#188]
Add T2 gear to Loot tables. And Add them to research terminal.

**Comment by zunath** [comment]
Do they need to be in the loot tables? I could see the components being available in the loot tables, but probably not the items themselves. Definitely research items though.

**Comment by taelon875** [comment]
Thinking on this not adding finished t2 to loot tables. I will add components when I go to add them in. (As planned) It can be considered when we have T3 gear in and areas to go with it.
