### ISSUE TITLE
Add a HARD label to the starting door for Zodiac

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#189]
Add a label to the Zodiac option on the starting door to signify it's essentially Hard mode. Lot of new players go there to begin with and find it difficult to survive. We should give them a warning, at the very least.

**Comment by taelon875** [comment]
That is on my todo list with the new player experience...

**Comment by zunath** [comment]
Ok didn't know if it was logged. Want me to close this one?

**Comment by taelon875** [comment]
No keep it open. I can just add this into a fast update and wont have to mess with my list,
