### ISSUE TITLE
Spells versus T2 gear

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#190]
I've been reading the wiki stats of abilities while updating the wiki and i reconized a few spells that will go too powerful with T2 gear (If they are still +8 to evoc/holy/enhancement), i have no objections about giving this much stats because some spells need them, but some others will become too powerful without any caps or restrictions.

Spells that caught my eye:
Poison:
Description: Inflicts poison on a single target for a limited time.

Base Mana Cost: 3

Base Casting Time: 2 seconds

Base Cool down: 6 seconds

--- 

Poison deals 3-7 damage per tick and decreases AC Dodge Bonus by 2

The unmodified spell deals damage for 3 ticks. (Each tick is 6 seconds).

For every 2 points of evocation affinity your character has, you gain an additional tick of damage.

For every 2 points of Intelligence your character has, you gain an additional tick of damage.

For every point of evocation magic bonus your character has from gear, you gain an additional tick of damage. 

---

Now having read this, you must also keep in mind that increasing the stats also increase the base damage of each tick. Let's say you have 8/10 evocation, 16 intelligence, and +8 to your gear in evocation...

4 + 3 + 8 = 15 rounds of poison damage, magnify the poison damage by how much the stats amplify them, and you can see the damage is ridiculously high, it is unavoidable, unresistable and can be cast at any range.

Suggestions: Make poison damage decay over each tick, each tick deal less and less damage, raise mana cost, make sure the spell cannot be stacked on a same target, raise the cooldown, add a DC resist for each tick which can nullify the tick completely.

--------

Refresh:
Description: Recovers the mana of a single target for a limited time.

Base Mana Cost: 15

Base Casting Time: 6 seconds

Base Cool down: 12 seconds

---

Refresh is an ability disc that allows you to more quickly recover your mana.

The unmodified power boosts mana by 2 points for 3 ticks. (Each tick is 6 seconds).

For every point of enhancement affinity your character has, you gain an additional tick of mana regen.

For every point of Wisdom your character has, you gain an additional tick of mana regen.

For every two points of enhancement magic bonus your character has from gear, you gain an additional tick of mana regen. 

---

This spell can make any mage auto sufficient with proper gear and that is a concern because it can come break the delicate balance of the mages gameplay.

Lets say we have 8/10 enhancement, 16 wisdom, +8 enhancement from gear:

3 + 8 + 6 + 4 = 21 ticks, that's 42 mana, any mage can walk off and be happy with such a self-recharging battery.

Suggestions: Cannot target self, cannot stack, the mana regenerated cannot go over 50% of the total mana pool of the target if it is above 15 mana, (So if you have 2/40 mana, you get casted a Refresh that recover 42 mana, it won't go above 22/40, but if you have 0/15, it will recover 15/15) Always allow a minimum of 15 mana to be recovered despite these conditions.

**Comment by taelon875** [comment]
Refresh is fine how it is, enhancement mages should have that Maybe some tweaking could be warranted, but until someone gets it in game, and uses it with decent skill. 

As for poison, I am most like going to be increasing the mana by a couple. But for the most part I think the damage is going to be staying the same for now. As of now, it doesn't count the mage as the killer, and it is one of the only high damage spells for mages, perhaps when we get more mage spells in we could revisit. But I'd rather not spend a majority of my mana to just kill one zombie, when people with guns might spend 8 bullets. And melee just chop down the swarm single handedly.

**Comment by Drakaden** [comment]
It might be good to have more viewpoints from other people about it, i don't want to debate it as my own concerns were already voiced.

**Comment by zunath** [comment]
Definitely leaving refresh as-is. It was always intended to replenish mana quickly and reliably. 

Poison I agree needs to have an increase mana cost. Collin's proposal is:

Mana Cost Increase to 8
Damage Ticks increased damage to 5-9

I'm in favor of increasing the mana cost, but not so much the amount of damage.

**Comment by zunath** [comment]
I think we've addressed this with the poison updates. Closing the ticket but let me know if we still need to do it, @taelon875
