### ISSUE TITLE
Animal companion

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#191]
I've noticed some players talking about wanting a summon/henchman dog to help them in discord, so i'm gonna throw some suggestions there:

Every player can own a dog, but it would need to be obtained from a quest (Think like dog trainer NPC who needs a hand with something)

Only one dog per player.

The dog have inferior stats to the player, he is a support companion, not made to replace the player.

Dogs are nimble, they can dodge blows easily (Translated to more AC)

If it is a summon we have to work with, dogs can be trained after a certain amount of gold or XP has been paid (XP from the dog, which he accumulate from doing anything in the environment, may it be fighting, tracking, helping with scavenging and so on) training them has 2 paths, one is level up it's general stats to be stronger/more skilled, the other is to give it a special perk, like bleeding bite, takedown and so on.

If it is a henchman we work with, the dog can level up like summons, but on top of that, the dog can be equipped with dog gear, making them even more customizable.

If your dog companion dies, it can either be on a cool down before you can summon it again, or have to go back to a camp to revive it.

**Comment by zunath** [comment]
It's an interesting idea, but I think I want companions to be summon-based rather than familiar based. We might investigate doing something like this at a later date, but for now I think it'll be summons only.
