### ISSUE TITLE
Redundant loot ID

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#194]
in the desert near the mine entrance, there is a couple vehicles in front with sandbags
the search spot near the vehicle has a redundant loot ID
it need to be changed

**Comment by Drakaden** [comment]
the center mine, east entrance, outside, i think it was either east desert or center, unsure

**Comment by taelon875** [comment]
This should be fixed, Open a new ticket if this persists.
