### ISSUE TITLE
Bug: Build Progress not saving properly

### ISSUE THREAD

**Issue by taelon875** [zunath/CyberpunkZombieSurvival_JVM#199]
Evidently players report that one restarts some building they create are reverting to their unfinished states even if they were complete when the server restarted.

Plus side items stored in chest when this takes place do save and return to chests once the chest is rebuilt.

**Comment by zunath** [comment]
Get me the character name, the location of the territory marker, and the type of object that was built but not saved please.

**Comment by taelon875** [comment]
Devana Carlson,  (Brelington) -Market Square - Commerce, Engineering Workbench, and one of the persistent chest is bugged.

**Comment by taelon875** [comment]
Noted that this is now throwing exceptions when players use the objects, this is heading to a Zunath fix this issue xD

It also is appearing on multiple characters in different areas. Seemingly random.

**Comment by zunath** [comment]
There were four construction sites affected by this. They weren't linked to their parent territory marker for some reason. I've hand-fixed these and logged #204 to cover fixing the root cause.
