### ISSUE TITLE
Natural Regeneration

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#200]
Suggesting either lowering the SP cost or buffing it's effects, starting at 3 SP and going up is too much for 6 seconds less per healing cycle.

If no benefits added, make it start at 1 SP.

Suggested added benefits: at 5/10 and 10/10, +1 to Infection DC, Bleed DC, +1 to healing cycle (example if you heal 2 hp per cycle, now it's 3), fastened infection fighting cycle.

Could also be raised to 15 ranks instead of 10, for 75% cycle, which translate to 45 seconds per healing tick, instead of 50% cap which is 1 minute per tick.

**Comment by zunath** [comment]
What's the underlying reasoning for this proposed change? Just that natural regeneration costs too much?

**Comment by taelon875** [comment]
I assume they mean it is not worth the cost...

**Comment by Drakaden** [comment]
Both assumptions are correct.

**Comment by Drakaden** [comment]
Sorry for my miscalculation, yes it would be too quick for a high health ticking character at 30 seconds, you are correct on that.

Though i would try to give Natural Regeneration more perks for justifying it's SP costs, if you don't want to lower it.

**Comment by zunath** [comment]
I don't want to change anything related to this at this time. I think it would change the nature of the upgrade.
