### ISSUE TITLE
T1 Guns crafting materials, T2 shotguns

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#209]
Currently T1 guns (Rifles, SMG, shotguns) take an equivalent of 60 iron to create (3 iron = 1 metal, 4 metal = 1 carbon fiber)

Suggesting lowering these materials to 3 carbon fiber and 3 metal (Instead of 4 carbon and 4 metal) That would lower the iron equivalent to 45.

I noticed the T2 shotguns are inexistant, they need made.

**Comment by taelon875** [comment]
I honestly think it is fine how it is, Carbon fiber is not hard to find, and iron is east to mine.

**Comment by zunath** [comment]
I'd rather introduce additional ways to get raw materials, like item scrapping instead of reducing the cost. Why is this suddenly a problem?

**Comment by Drakaden** [comment]
You got a point Zunath, i was talking to the 3 italian players i was helping earlier on voice chat and they were finding the quantity of iron equivalent to be steep, and i did too after trying to make some, it's a lot of iron.

But once recycling is in i suppose it won't be as problematic.

**Comment by zunath** [comment]
Not taking any action on this one.
