### ISSUE TITLE
Caustic & Mana veins

### ISSUE THREAD

**Issue by Drakaden** [zunath/CyberpunkZombieSurvival_JVM#221]
Just suggestions on how we could implement them in-game, this is not meant to force them in, just ideas, i know right now you guys are on the fence about it because they would come give too many ressources.

---

Lower the yield per node: from 3 - 5 (standard yield) to 2-3.
Not as common as standard nodes (A mine would yield a lot of iron & thorium veins, but only 1 or 2 veins of those)
Add them in hard to reach places (Examples: Southwest area of the desert, this is a very hard to access place, the B3 of the solarian ruins, on the bridges ends)
Slghtly longer respawn rate than standard veins (Not THAT much longer, i was thinking maybe double the respawn time)

**Comment by zunath** [comment]
These are going to remain DM-only for now.
