### ISSUE TITLE
Add food contribution erf

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#85]
[ZS_food_G.zip](https://github.com/zunath/CyberpunkZombieSurvival_JVM/files/1673424/ZS_food_G.zip)

A player has donated an erf containing changes to food items. Add this ERF to the module (both 1.69 and 1.74) and update any DB references as needed.

**Comment by Drakaden** [comment]
FOod imported in module and module sent to Zunath.
