### ISSUE TITLE
Add area donations provided by Boots

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#86]
Player Boots has provided areas in her module for us to install into our server.

This one might be more complicated because the haks are different, but still worth a shot to see if we can lift them.

Module Link: http://www.mediafire.com/file/nol6k0z78lhoozf/NZS0719G9.mod

Hak Links:

http://www.mediafire.com/file/8q0i8kayktrsg98/re_creatures.hak
http://www.mediafire.com/file/usq3bndcl9k6xl9/udp1_subext.hak
http://www.mediafire.com/file/gqb6i63hk7gp77c/necro_head.zip
http://www.mediafire.com/file/2cs92z2a14v91zu/necro_tilesets.hak
http://www.mediafire.com/file/trrcc77cgywlkh3/necro_cloth.hak
http://www.mediafire.com/file/pujh59dn4idc09n/necro_tile.hak
http://www.mediafire.com/file/lsgtvg4bwio4vdo/necro_creature.hak
http://www.mediafire.com/file/fp1f7ckg211dcs9/necro_placeable.hak
http://www.mediafire.com/file/x1m3kq7iri29223/necro_load.hak
http://www.mediafire.com/file/nkdaorjq29hwrkb/necro_item.hak
http://www.mediafire.com/file/umycb24i6d2jb8j/necro3_top.hak
http://www.mediafire.com/file/byhuwy0o0qhflm5/necro3_base.hak

**Comment by Drakaden** [comment]
Missing file: necro_portrait, decided to trash contribution.
