### ISSUE TITLE
Death System: Add more ways to revive

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#89]
- Add boss monsters which drop items used for creating revival stones.
- Add a way to revive individual (logged in) players from the death realm. Maybe a quest similar to the one in classic ZS where gems were used at the appropriate altar and a portal appeared.

**Comment by Drakaden** [comment]
Suggestion: Rare chance to find a component to craft a stone on every search site, this chance happens even on failures, but it only have 1 roll per search even if the player has many search attempt, and the chance would be like 1/1000.

**Comment by zunath** [comment]
I've added a revival stone for DMs to grant for good RP during quests. We'll start with that and then see if we need to expand it to be part of rewards in other aspects of the game.
